-- ============================================================================
-- audit/0001 — GrowClinic Audit tool baseline (PostgreSQL)
--
-- Executed by the migrate job with `SET LOCAL ROLE audit_owner`, so every
-- object is owned by audit_owner; audit_app gets DML through the grants step.
--
-- Source: the MySQL CREATE TABLE + ~40 boot-time `ALTER TABLE ADD COLUMN`
-- statements in the old apps/audit/db.js, collapsed into their final shape.
-- Deliberate type decisions (see DATABASE-MIGRATION.md §3):
--   • INT AUTO_INCREMENT      → integer GENERATED BY DEFAULT AS IDENTITY
--                               (BY DEFAULT so imported ids are preserved)
--   • TINYINT 0/1 flags       → smallint + CHECK (0,1). NOT boolean: the CRM
--                               API, webhooks and admin UI exchange 0/1.
--   • DATETIME                → timestamptz(0) (session/database TZ is UTC)
--   • MEDIUMTEXT              → text (JSON-in-text columns stay text: the app
--                               JSON.parse()s them itself)
--   • VARCHAR for values the app truncates or controls → kept as varchar(n);
--     free text that arrives un-truncated (AI extraction, inbound webhooks,
--     user profile edits) → text, so an over-long value can't fail a write.
--   • MySQL _ci collation     → case-insensitive username uniqueness via a
--                               unique index on lower(username); searches use ILIKE.
--   • Implicit relations      → foreign keys added NOT VALID: enforced for all
--     new writes, while legacy orphan rows (if any) are kept on import and
--     reported by database/import/validate.sql instead of blocking it.
-- ============================================================================

CREATE OR REPLACE FUNCTION audit.set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW."updatedAt" := CURRENT_TIMESTAMP;
  RETURN NEW;
END $$;

-- ── leads (legacy flat lead log) ────────────────────────────────────────────
CREATE TABLE audit.leads (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text,
  "clinicName"    text,
  "clinicType"    text,
  city            text,
  website         text,
  phone           text,
  "googleTraffic" text,
  ads             text,
  "monthlyVolume" text,
  "primaryGoal"   text,
  "auditScore"    integer DEFAULT 0,
  "reportUrl"     text,
  "createdAt"     timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_leads_created ON audit.leads ("createdAt");

-- ── settings (admin-managed keys; values may be secrets) ────────────────────
CREATE TABLE audit.settings (
  "keyName"   varchar(128) PRIMARY KEY,
  "keyValue"  text,
  "updatedAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);

-- ── admin_users (CRM staff; scrypt hashes, per-user TOTP, invites) ──────────
CREATE TABLE audit.admin_users (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username        varchar(64)  NOT NULL,
  "passwordHash"  varchar(255) NOT NULL,
  role            varchar(20)  NOT NULL DEFAULT 'caller',
  active          smallint     DEFAULT 1 CHECK (active IN (0, 1)),
  "createdAt"     timestamptz(0) DEFAULT CURRENT_TIMESTAMP,
  "lastLoginAt"   timestamptz(0),
  email           varchar(255),
  "totpSecret"    varchar(64),
  "totpEnabled"   smallint DEFAULT 0 CHECK ("totpEnabled" IN (0, 1)),
  "totpPending"   varchar(64),
  "inviteToken"   varchar(64),
  "inviteExpires" bigint,
  "displayName"   text,
  "avatarUrl"     text,
  designation     text,
  department      text,
  linkedin        text,
  phone           text,
  location        text,
  "joinDate"      date
);
CREATE UNIQUE INDEX uq_admin_users_username_ci ON audit.admin_users (lower(username));
CREATE INDEX idx_admin_users_invite ON audit.admin_users ("inviteToken") WHERE "inviteToken" IS NOT NULL;

-- ── chat_sessions (the CRM lead record) ─────────────────────────────────────
CREATE TABLE audit.chat_sessions (
  "sessionId"       varchar(64) PRIMARY KEY,
  "startedAt"       timestamptz(0) DEFAULT CURRENT_TIMESTAMP,
  "lastActivityAt"  timestamptz(0) DEFAULT CURRENT_TIMESTAMP,
  completed         smallint DEFAULT 0 CHECK (completed IN (0, 1)),
  "userMsgCount"    integer DEFAULT 0,
  "aiMsgCount"      integer DEFAULT 0,
  "clinicName"      text,
  "userName"        text,
  city              text,
  phone             text,
  "websiteUrl"      text,
  "leadCaptured"    smallint DEFAULT 0 CHECK ("leadCaptured" IN (0, 1)),
  "reportUrl"       text,
  transcript        text,
  "ipHash"          varchar(64),
  "userAgent"       varchar(255),
  source            varchar(64),
  channel           varchar(64),
  campaign          text,
  verified          smallint DEFAULT 0 CHECK (verified IN (0, 1)),
  "otpSent"         smallint DEFAULT 0 CHECK ("otpSent" IN (0, 1)),
  "returningClient" smallint DEFAULT 0 CHECK ("returningClient" IN (0, 1)),
  "reportViewed"    smallint DEFAULT 0 CHECK ("reportViewed" IN (0, 1)),
  "crmStatus"       varchar(24),
  "crmNotes"        text,
  "crmUpdatedAt"    timestamptz(0),
  "crmFollowUpAt"   timestamptz(0),
  email             text,
  country           text,
  specialty         text,
  "crmRating"       varchar(8),
  "crmDealValue"    integer,
  "crmRemarks"      text,          -- JSON array of {by, at, text}
  "crmTags"         varchar(255),  -- comma-separated tags (validated ≤255)
  "lostReason"      varchar(64),
  "crmAiSummary"    text,          -- JSON {at, summary, extraction, suggestedTags}
  "gcalEventId"     text,
  "ownerId"         integer,
  "assignedAt"      timestamptz(0),
  "phoneE164"       varchar(20),
  gclid             text,
  fbclid            text,
  "landingPage"     text,
  referrer          text,
  "adGroup"         text,
  keyword           text
);
CREATE INDEX idx_chat_started   ON audit.chat_sessions ("startedAt");
CREATE INDEX idx_chat_completed ON audit.chat_sessions (completed);
CREATE INDEX idx_phone_e164     ON audit.chat_sessions ("phoneE164");
CREATE INDEX idx_chat_owner     ON audit.chat_sessions ("ownerId");
ALTER TABLE audit.chat_sessions
  ADD CONSTRAINT fk_chat_sessions_owner FOREIGN KEY ("ownerId")
  REFERENCES audit.admin_users (id) ON DELETE SET NULL NOT VALID;

-- ── admin_sessions ──────────────────────────────────────────────────────────
CREATE TABLE audit.admin_sessions (
  token       varchar(64) PRIMARY KEY,
  "createdAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP,
  "expiresAt" bigint NOT NULL,              -- epoch milliseconds
  "ipHash"    varchar(64),
  "userId"    integer,                      -- NULL for the legacy single-password admin
  role        varchar(20)
);
CREATE INDEX idx_admin_sessions_user ON audit.admin_sessions ("userId");
ALTER TABLE audit.admin_sessions
  ADD CONSTRAINT fk_admin_sessions_user FOREIGN KEY ("userId")
  REFERENCES audit.admin_users (id) ON DELETE CASCADE NOT VALID;

-- ── admin_login_attempts ────────────────────────────────────────────────────
CREATE TABLE audit.admin_login_attempts (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ipHash"      varchar(64) NOT NULL,
  "attemptedAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP,
  success       smallint DEFAULT 0 CHECK (success IN (0, 1))
);
CREATE INDEX idx_admin_attempts ON audit.admin_login_attempts ("ipHash", "attemptedAt");

-- ── popup_leads (website / popup soft leads) ────────────────────────────────
CREATE TABLE audit.popup_leads (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          varchar(255),
  phone         varchar(64),
  email         varchar(255),
  source        varchar(32),
  "sessionId"   varchar(64),
  "utmSource"   varchar(128),
  "utmCampaign" varchar(128),
  referrer      varchar(512),
  converted     smallint DEFAULT 0 CHECK (converted IN (0, 1)),
  "ipHash"      varchar(64),
  "createdAt"   timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_popup_created ON audit.popup_leads ("createdAt");
CREATE INDEX idx_popup_session ON audit.popup_leads ("sessionId");

-- ── admin_logs ──────────────────────────────────────────────────────────────
CREATE TABLE audit.admin_logs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action      varchar(64) NOT NULL,
  detail      varchar(512),
  "ipHash"    varchar(64),
  "createdAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_admin_logs ON audit.admin_logs ("createdAt");

-- ── api_usage (AI / Google API cost + health) ───────────────────────────────
CREATE TABLE audit.api_usage (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider           varchar(64) NOT NULL,
  model              varchar(128),
  operation          varchar(64),
  "sessionId"        varchar(64),
  "promptTokens"     integer DEFAULT 0,
  "completionTokens" integer DEFAULT 0,
  "totalTokens"      integer DEFAULT 0,
  requests           integer DEFAULT 1,
  success            smallint DEFAULT 1 CHECK (success IN (0, 1)),
  error              text,
  "loggedAt"         timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_usage_logged   ON audit.api_usage ("loggedAt");
CREATE INDEX idx_usage_provider ON audit.api_usage (provider, "loggedAt");

-- ── lead_tasks (CRM to-dos; completed, never deleted) ───────────────────────
-- sessionId is a soft reference (no FK): tasks/events are written by
-- fire-and-forget paths that can race the chat_sessions insert, and deleting a
-- lead has always kept its history rows.
CREATE TABLE audit.lead_tasks (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessionId" varchar(64),
  title       varchar(255),
  "dueAt"     timestamptz(0),
  "doneAt"    timestamptz(0),
  "createdBy" varchar(40),
  "createdAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_task_session ON audit.lead_tasks ("sessionId");
CREATE INDEX idx_task_due     ON audit.lead_tasks ("dueAt");

-- ── lead_events (append-only Lead 360 timeline; soft reference) ─────────────
CREATE TABLE audit.lead_events (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessionId" varchar(64),
  type        varchar(32),
  detail      varchar(512),
  actor       varchar(40),
  at          timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_event_session ON audit.lead_events ("sessionId");

-- ── raw_events (verbatim inbound payloads for audit + replay) ───────────────
CREATE TABLE audit.raw_events (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel      varchar(32),
  "sessionId"  varchar(64),
  payload      text,
  status       varchar(16) DEFAULT 'ok',
  "receivedAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_raw_channel ON audit.raw_events (channel, "receivedAt");

-- ── automation_rules / automation_runs ──────────────────────────────────────
CREATE TABLE audit.automation_rules (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        varchar(120),
  "trigger_"  varchar(32),
  conditions  text,   -- JSON
  actions     text,   -- JSON
  enabled     smallint DEFAULT 1 CHECK (enabled IN (0, 1)),
  "createdBy" varchar(40),
  "createdAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit.automation_runs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruleId"    integer,
  "sessionId" varchar(64),
  "trigger_"  varchar(32),
  result      varchar(255),
  "dryRun"    smallint DEFAULT 0 CHECK ("dryRun" IN (0, 1)),
  at          timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_auto_runs ON audit.automation_runs ("ruleId", at);
ALTER TABLE audit.automation_runs
  ADD CONSTRAINT fk_automation_runs_rule FOREIGN KEY ("ruleId")
  REFERENCES audit.automation_rules (id) ON DELETE SET NULL NOT VALID;

-- ── failed_crm_events (retry queue for n8n / sheets / telegram webhooks) ────
CREATE TABLE audit.failed_crm_events (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event         varchar(64) NOT NULL,
  "sessionId"   varchar(64) NOT NULL,
  target        varchar(32) NOT NULL,
  payload       text NOT NULL,
  attempts      integer DEFAULT 0,
  "nextRetryAt" timestamptz(0) NOT NULL,
  "lastError"   varchar(512),
  "createdAt"   timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_crm_retry ON audit.failed_crm_events ("nextRetryAt");

-- ── Employee workspace: xp_ledger, checkins, notification_prefs ─────────────
CREATE TABLE audit.xp_ledger (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"    integer NOT NULL,
  event       varchar(48) NOT NULL,
  points      integer NOT NULL,
  "refId"     varchar(96),
  "createdAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_xp_user ON audit.xp_ledger ("userId", "createdAt");
ALTER TABLE audit.xp_ledger
  ADD CONSTRAINT fk_xp_ledger_user FOREIGN KEY ("userId")
  REFERENCES audit.admin_users (id) ON DELETE CASCADE NOT VALID;

CREATE TABLE audit.checkins (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"      integer NOT NULL,
  "checkinDate" date NOT NULL,
  "checkinType" varchar(10) NOT NULL,
  payload       text,
  "createdAt"   timestamptz(0) DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uniq_checkin UNIQUE ("userId", "checkinDate", "checkinType")
);
CREATE INDEX idx_checkin_user ON audit.checkins ("userId", "checkinDate");
ALTER TABLE audit.checkins
  ADD CONSTRAINT fk_checkins_user FOREIGN KEY ("userId")
  REFERENCES audit.admin_users (id) ON DELETE CASCADE NOT VALID;

CREATE TABLE audit.notification_prefs (
  "userId"    integer NOT NULL,
  "notifKey"  varchar(48) NOT NULL,
  enabled     smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  "updatedAt" timestamptz(0) DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("userId", "notifKey")
);
CREATE INDEX idx_notif_key ON audit.notification_prefs ("notifKey");
ALTER TABLE audit.notification_prefs
  ADD CONSTRAINT fk_notification_prefs_user FOREIGN KEY ("userId")
  REFERENCES audit.admin_users (id) ON DELETE CASCADE NOT VALID;
-- was: updatedAt ... ON UPDATE CURRENT_TIMESTAMP
CREATE TRIGGER trg_notification_prefs_updated_at
  BEFORE UPDATE ON audit.notification_prefs
  FOR EACH ROW EXECUTE FUNCTION audit.set_updated_at();
