/**
 * Core utility for sending WhatsApp messages via Meta Graph API.
 * Includes specialized formatters for audit reports and contact confirmations.
 */

interface AuditReportData {
  seoScore: number;
  competitorRank: number;
  estimatedLeads: number;
  localVisibilityScore: number;
  websiteHealthScore: number;
  googleBusinessStatus: string;
  roadmap: string[];
}

interface AuditFormData {
  fullName: string;
  clinicName: string;
  specialization: string;
  city: string;
  website?: string;
  pinCode?: string;
}

async function sendWhatsAppTextMessage(to: string, message: string) {
  const cleanNumber = to.replace(/\D/g, "");

  const apiUrl = process.env.WHATSAPP_API_URL;
  const apiToken = process.env.WHATSAPP_API_TOKEN;

  if (!apiUrl || !apiToken) {
    console.warn("WhatsApp API credentials are not configured. Message not sent.");
    return { success: false, error: "Missing configuration" };
  }

  try {
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messaging_product: "whatsapp",
        to: cleanNumber,
        type: "text",
        text: { body: message },
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      console.error("WhatsApp API Error:", data);
      return { success: false, error: data };
    }

    console.log(`WhatsApp message sent successfully to ${cleanNumber}`);
    return { success: true, data };
  } catch (error) {
    console.error("Failed to send WhatsApp message:", error);
    return { success: false, error };
  }
}

/**
 * Sends a formatted audit report summary via WhatsApp.
 */
export async function sendAuditReportWhatsApp(
  phone: string,
  report: AuditReportData,
  formData: AuditFormData
) {
  const scoreEmoji = (score: number) => {
    if (score >= 70) return "🟢";
    if (score >= 40) return "🟡";
    return "🔴";
  };

  const message = `🏥 *GrowClinic — Digital Health Audit Report*
━━━━━━━━━━━━━━━━━━━━━━

Hi *${formData.fullName}*,
Your audit for *${formData.clinicName}* (${formData.specialization}) in *${formData.city}* is complete.

📊 *Overall SEO Score:* ${scoreEmoji(report.seoScore)} *${report.seoScore}/100*

📍 *Map Visibility:* ${scoreEmoji(report.localVisibilityScore)} ${report.localVisibilityScore}%
🌐 *Website Health:* ${scoreEmoji(report.websiteHealthScore)} ${report.websiteHealthScore}%
🏪 *GMB Status:* ${report.googleBusinessStatus}
📈 *Competitor Rank:* #${report.competitorRank} in your area
⚠️ *Missed Potential:* ~${report.estimatedLeads} local searches/mo lost

🚀 *Your 90-Day Action Plan:*
${report.roadmap.map((item, i) => `${i + 1}. ${item}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━
💬 Want to discuss this report with a growth strategist?
📞 Call: +91 72877 74212
🌐 Visit: https://www.growclinic.io/contact

_This report was generated by GrowClinic's data-driven audit engine._`;

  return sendWhatsAppTextMessage(phone, message);
}

/**
 * Sends a contact form confirmation via WhatsApp.
 */
export async function sendContactConfirmationWhatsApp(phone: string, name: string) {
  const message = `👋 Hi *${name}*!

Thank you for reaching out to *GrowClinic*. We've received your inquiry and our growth engineering team will get back to you within *2 hours*.

In the meantime, you can:
🔍 Book a free clinic strategy session at https://www.growclinic.io/#book
📞 Call us directly: +91 72877 74212

_— The GrowClinic Team_`;

  return sendWhatsAppTextMessage(phone, message);
}

// Keep the original generic export for backward compatibility
export { sendWhatsAppTextMessage as sendWhatsAppMessage };
